name: ""

connection:
  url: ""
  api_query_path: ""
  timeout: 30

queries:
  - name: ""
    type: "query"
    promql: |
      ""
    export_config: #Optional
      export_all_metric: false
      export_metric_key:
        - ""

  - name: ""
    type: "query_range"
    promql: |
      ""
    # Require for query_range
    start: "30d"
    end: "now"
    step: "5m"
    export_config: #Optional
      export_all_metric: false
      export_metric_key:
        - ""
    workflows: #Optional
      internal:
        - ""

# Can see sample config in config_template
internal_workflows: #Optional
  - {}

output: #Optional
  print_output: false
  write_options: #Optional
    - base_directory: "./results"
      format: csv
    - base_directory: "./results"
      format: json